# masyvai ir matricos

In [1]:
import numpy as np

In [5]:
sarasas = [4, 7, 11, 6, 9, 69, 420, 777, 31]

In [6]:
masyvas = np.array(sarasas)
print(masyvas, type(masyvas))

[  4   7  11   6   9  69 420 777  31] <class 'numpy.ndarray'>


In [7]:
sugrupuotas = [[4, 7, 11], [6, 9, 69], [420, 777, 31]]

In [8]:
matrica = np.array(sugrupuotas)
print(matrica)

[[  4   7  11]
 [  6   9  69]
 [420 777  31]]


In [9]:
imtis = np.arange(0, 30, 3)
print(imtis, type(imtis))

[ 0  3  6  9 12 15 18 21 24 27] <class 'numpy.ndarray'>


In [10]:
nuliai = np.zeros(10)
print(nuliai)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
nuliai_6x6 = np.zeros((6, 6))
nuliai_6x6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
akis = np.eye(6)
akis

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
akis[0][1] = 3
akis[1][0] = 2

In [22]:
akis

array([[1., 3., 0., 0., 0., 0.],
       [2., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [26]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [27]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [29]:
np.linspace(0, 1, 4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [30]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

# random arrays

In [31]:
np.random.rand(10)

array([0.10449246, 0.31221686, 0.88582861, 0.21378306, 0.96543372,
       0.29231906, 0.11714494, 0.71963677, 0.39052074, 0.16114324])

In [39]:
np.random.rand(5, 5)

array([[0.23003778, 0.66511197, 0.31548966, 0.60463293, 0.83833158],
       [0.86959445, 0.13129179, 0.33158288, 0.27378742, 0.18733794],
       [0.71297164, 0.65935473, 0.86538641, 0.60776494, 0.82955354],
       [0.169408  , 0.24690778, 0.8644949 , 0.90103582, 0.2257986 ],
       [0.84158307, 0.68311104, 0.56398559, 0.13889718, 0.39459251]])

In [37]:
np.random.randn(5, 5) * 100

array([[ 155.69135428,  111.95136738,  -97.55061019,  137.30069096,
          43.57550961],
       [ -80.74675496,  116.49075789,  -79.94857511,  -10.86060109,
        -120.72938004],
       [ -92.75631789,  153.42990019,  206.27434545,  197.7131889 ,
         -11.48631823],
       [  52.2018152 ,  157.14800132,  -40.23447259,  -93.78628229,
         165.41901306],
       [ 132.82143873,  -73.41996965,  -53.58347236,  -22.05955275,
         126.27885285]])

In [40]:
np.random.randint(100, 200, 10)

array([168, 172, 159, 104, 141, 152, 153, 195, 168, 193])

# masyvu pertvarka

In [86]:
bekto_64 = np.random.randint(100, 999, 64)
bekto_64

array([848, 533, 765, 704, 628, 149, 262, 665, 427, 693, 835, 972, 450,
       148, 661, 643, 487, 545, 485, 529, 547, 687, 408, 888, 575, 816,
       720, 284, 676, 114, 527, 124, 824, 280, 785, 896, 813, 856, 201,
       998, 375, 557, 709, 517, 444, 275, 425, 598, 529, 493, 732, 658,
       731, 448, 854, 558, 150, 221, 979, 439, 216, 341, 826, 152])

In [87]:
betko_8x8 = bekto_64.reshape(8, 8)
print(betko_8x8)

[[848 533 765 704 628 149 262 665]
 [427 693 835 972 450 148 661 643]
 [487 545 485 529 547 687 408 888]
 [575 816 720 284 676 114 527 124]
 [824 280 785 896 813 856 201 998]
 [375 557 709 517 444 275 425 598]
 [529 493 732 658 731 448 854 558]
 [150 221 979 439 216 341 826 152]]


In [44]:
betko_20 = np.random.randint(100, 999, 20)
betko_4x5 = betko_20.reshape(4, 5)
print(betko_4x5)

[[850 515 691 415 803]
 [755 587 957 829 895]
 [691 924 666 158 664]
 [212 937 168 934 500]]


# naudingi metodai

In [46]:
print(min(bekto_64))
print(bekto_64.min())

166
166


In [47]:
betko_8x8.max()

998

In [48]:
print(betko_20.argmin(), betko_20.min())

13 158


In [49]:
betko_8x8.argmax()

52

In [54]:
kvadratas = np.zeros((5, 5, 5)).astype(int) + 1
print(kvadratas)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [55]:
betko_8x8.shape

(8, 8)

In [56]:
betko_20.shape

(20,)

In [57]:
betko_4x5.dtype

dtype('int64')

# indeksacija ir reikšmių traukimas

In [58]:
betko_20

array([850, 515, 691, 415, 803, 755, 587, 957, 829, 895, 691, 924, 666,
       158, 664, 212, 937, 168, 934, 500])

In [61]:
betko_20[2:5]

array([691, 415, 803])

In [62]:
betko_20[::2]

array([850, 691, 803, 587, 829, 691, 666, 664, 937, 934])

In [64]:
betko_20[-5] = 777
betko_20

array([850, 515, 691, 415, 803, 755, 587, 957, 829, 895, 691, 924, 666,
       158, 664, 777, 937, 168, 934, 500])

In [65]:
betko_8x8

array([[305, 900, 556, 727, 472, 638, 364, 233],
       [240, 937, 518, 270, 908, 979, 318, 435],
       [692, 312, 790, 494, 337, 794, 381, 309],
       [193, 776, 564, 734, 187, 698, 318, 410],
       [503, 434, 309, 662, 887, 713, 986, 800],
       [820, 166, 701, 169, 295, 351, 989, 565],
       [604, 492, 222, 851, 998, 557, 696, 909],
       [689, 342, 784, 647, 912, 794, 507, 552]])

In [68]:
betko_8x8[2,2:5]

array([790, 494, 337])

In [69]:
betko_8x8[2:-2, 2:-2]

array([[790, 494, 337, 794],
       [564, 734, 187, 698],
       [309, 662, 887, 713],
       [701, 169, 295, 351]])

In [70]:
betko_8x8[-3:, -3:]

array([[351, 989, 565],
       [557, 696, 909],
       [794, 507, 552]])

In [71]:
betko_4x5[-3:, -3:]

array([[957, 829, 895],
       [666, 158, 664],
       [168, 934, 500]])

# traukimas pagal sąlygą

In [88]:
tiesa_8x8 = betko_8x8 > 500
tiesa_8x8

array([[ True,  True,  True,  True,  True, False, False,  True],
       [False,  True,  True,  True, False, False,  True,  True],
       [False,  True, False,  True,  True,  True, False,  True],
       [ True,  True,  True, False,  True, False,  True, False],
       [ True, False,  True,  True,  True,  True, False,  True],
       [False,  True,  True,  True, False, False, False,  True],
       [ True, False,  True,  True,  True, False,  True,  True],
       [False, False,  True, False, False, False,  True, False]])

In [89]:
dideli = betko_8x8[tiesa_8x8]

In [74]:
betko_8x8[betko_8x8 < 200]

array([193, 187, 166, 169])

In [90]:
dideli.shape

(39,)

In [80]:
dideli.reshape(19, 2)

array([[900, 556],
       [727, 638],
       [937, 518],
       [908, 979],
       [692, 790],
       [794, 776],
       [564, 734],
       [698, 503],
       [662, 887],
       [713, 986],
       [800, 820],
       [701, 989],
       [565, 604],
       [851, 998],
       [557, 696],
       [909, 689],
       [784, 647],
       [912, 794],
       [507, 552]])

# elgsenos ypatumai

In [91]:
betko_20

array([850, 515, 691, 415, 803, 755, 587, 957, 829, 895, 691, 924, 666,
       158, 664, 777, 937, 168, 934, 500])

In [95]:
ispjova = betko_20[5:-5]
ispjova

array([755, 587, 957, 829, 895, 691, 924, 666, 158, 664])

In [96]:
ispjova[:] = 999

In [97]:
betko_20

array([850, 515, 691, 415, 803, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 937, 168, 934, 500])

In [98]:
kopija = betko_20.copy()
kopija

array([850, 515, 691, 415, 803, 999, 999, 999, 999, 999, 999, 999, 999,
       999, 999, 777, 937, 168, 934, 500])

In [99]:
kopija == betko_20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [104]:
kopijos_ispjova = kopija[5:-5]
kopijos_ispjova.shape

(10,)

In [105]:
kopijos_ispjova[:] = np.random.randint(100, 999, 10)

In [106]:
kopija

array([850, 515, 691, 415, 803, 826, 788, 951, 427, 555, 536, 118, 147,
       395, 296, 777, 937, 168, 934, 500])

In [107]:
kopija == betko_20

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True])

# matematines operacijos

In [108]:
pirmi_10 = np.random.randint(0, 99, 10)
antri_10 = np.random.randint(0, 99, 10)
print(pirmi_10, antri_10)

[51  7 53 19 29 95 54 53 13 64] [69 64 72 59 67 94 16 44 89 83]


In [111]:
sudetis = pirmi_10 + antri_10
sudetis

array([120,  71, 125,  78,  96, 189,  70,  97, 102, 147])

In [113]:
daugyba = pirmi_10 * antri_10
daugyba

array([3519,  448, 3816, 1121, 1943, 8930,  864, 2332, 1157, 5312])

In [115]:
dalyba = antri_10 / pirmi_10
dalyba

array([1.35294118, 9.14285714, 1.35849057, 3.10526316, 2.31034483,
       0.98947368, 0.2962963 , 0.83018868, 6.84615385, 1.296875  ])

In [120]:
kubu = pirmi_10 ** 8
kubu

array([  45767944570401,          5764801,   62259690411361,
            16983563041,     500246412961, 6634204312890625,
         72301961339136,   62259690411361,        815730721,
        281474976710656])

In [121]:
np.sin(pirmi_10)

array([ 0.67022918,  0.6569866 ,  0.39592515,  0.14987721, -0.66363388,
        0.68326171, -0.55878905,  0.39592515,  0.42016704,  0.92002604])

In [123]:
print(pirmi_10, np.log(pirmi_10))

[51  7 53 19 29 95 54 53 13 64] [3.93182563 1.94591015 3.97029191 2.94443898 3.36729583 4.55387689
 3.98898405 3.97029191 2.56494936 4.15888308]


Uzduotys

In [1]:
import numpy as np

In [2]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.ones(10) * 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [6]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [7]:
arr = np.arange(1,26).reshape(5,5)

In [8]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
arr[4,3]

24

In [11]:
arr[-1]

array([21, 22, 23, 24, 25])

In [12]:
arr[:3, :3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [13]:
arr[1:4, 1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [14]:
arr[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

In [15]:
randarr = np.random.rand(20)

In [16]:
randarr

array([0.69000334, 0.81823215, 0.44644875, 0.94171465, 0.71086677,
       0.04395011, 0.59828149, 0.1558245 , 0.97109869, 0.58371885,
       0.85421505, 0.87423366, 0.61485772, 0.60971421, 0.90827344,
       0.43441214, 0.12176893, 0.25789931, 0.39631333, 0.66905034])

In [17]:
max(randarr)

0.9710986857908004

In [18]:
randarr.argmax()

8

In [19]:
randarr.min()

0.043950112589955626

In [20]:
randarr.argmin()

5

In [21]:
randarr.dtype

dtype('float64')

In [25]:
bandymas = np.arange(-1,101)

In [26]:
bandymas

array([ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
        12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,
        25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,
        77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,
        90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
bandymas[bandymas > 90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [28]:
bandymas[bandymas % 7 == 0]

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [29]:
np.linspace(0.025,1,40).reshape(5,8)

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [30]:
matrica = np.arange(2,1000)

In [31]:
res = matrica[(matrica ** 0.5) % 1 == 0].reshape(6,5)

In [32]:
res

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

In [33]:
testlist = np.arange(1,101)

In [34]:
def is_prime(number):
    for i in range(2, number):
        if number % i == 0:
            return False
    return True

In [35]:
vis_prime = np.vectorize(is_prime)

In [36]:
testlist[vis_prime(testlist)]

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])